### PR TITLE
Add macOS and other OS support in run.sh, install.sh and MAKEFILE

### PR DESCRIPTION
**Pull request by uimaxbai**
### Added:

- macOS support
- Multiple package manager installs

### CODE REVIEW

**Comment by werdl** [comment]
Please fix working tree, also please outline which files have changed and why, thanks!

**Comment by uimaxbai** [comment]
All in title, only files that (should) be changed are `run.sh`, `install.sh`, and `MAKEFILE`

**Comment by uimaxbai** [comment]
Will sort out build remenants by adding to .gitignore

**Comment by uimaxbai** [comment]
Alright, all config files should have been cleared.

**Comment by uimaxbai** [comment]
Now changed .gitignore.

**Pull request merged**
